#!/usr/bin/env bash

cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/artifact_resolution_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/aspect_common_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/assertion_consumer_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/assertion_id_request_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/attribute_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/attribute_consuming_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/attribute_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/contact_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/description_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/digest_method_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/disco_hints_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/disco_ui_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/discovery_response_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/domain_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/encryption_method_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/entity_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/entity_attribute_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/geolocation_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/idp_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/information_url_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/key_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/keywords_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/logo_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/manage_nameid_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/nameid_format_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/nameid_mapping_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/network_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/null_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/organization_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/organization_displayname_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/organization_name_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/organization_url_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/privacy_url_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/protocol_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/publication_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/registration_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/registration_policy_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/request_initiator_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/requested_attribute_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/scope_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/service_description_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/service_name_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/signing_method_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/single_logout_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/single_signon_service_test.exs
cp test/smee_view/aspects/displayname_test.exs test/smee_view/aspects/sp_test.exs
