#!/usr/bin/env bash

cp test/smee_view/views/artifact_resolution_services_test.exs  test/smee_view/views/assertion_consumer_services_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs  test/smee_view/views/assertion_id_request_service_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs  test/smee_view/views/attribute_consuming_services_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs  test/smee_view/views/attribute_services_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/attributes_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/contacts_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/descriptions_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/digest_methods_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/disco_hints_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/disco_uis_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/discovery_response_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/displaynames_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/domains_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/encryption_methods_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/entities_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/entity_attributes_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/geolocations_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/idps_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/information_urls_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/keys_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/keywords_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/logos_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/manage_nameid_services_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/nameid_formats_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/nameid_mapping_service_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/networks_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/organization_displaynames_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/organization_names_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/organization_urls_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/organizations_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/privacy_urls_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/protocols_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/publication_path_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/registration_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/registration_policies_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/request_initiators_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/requested_attributes_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/scopes_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/service_descriptions_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/service_names_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/signing_methods_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/single_logout_services_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/single_signon_services_test.exs
cp test/smee_view/views/artifact_resolution_services_test.exs   test/smee_view/views/sps_test.exs
